import { internalMutation } from "./_generated/server";

export const seedDailyDeals = internalMutation({
  args: {},
  handler: async (ctx) => {
    const deals = [
      {
        route: "JFK ↔ FCO",
        origin: "New York JFK",
        destination: "Rome Fiumicino",
        airline: "Norse Atlantic",
        price: 338,
        outboundDuration: "8h 15m",
        outboundStops: 0,
        returnDuration: "9h 30m",
        returnStops: 0,
        departureDate: "Jan 15, 2026",
        returnDate: "Jan 29, 2026",
        priceScore: 95,
        comfortScore: 85,
        speedScore: 90,
        notes: "Direct Norse Atlantic red-eye—crash in a Trastevere hostel by noon. Premium economy legroom at economy prices!",
        bookingUrl: "https://trip.com/flights/book?deal=jfk-fco-338",
        featured: true,
      },
      {
        route: "DEL ↔ DXB",
        origin: "Delhi",
        destination: "Dubai",
        airline: "Air India Express",
        price: 189,
        outboundDuration: "3h 25m",
        outboundStops: 0,
        returnDuration: "3h 35m",
        returnStops: 0,
        departureDate: "Jan 10, 2026",
        returnDate: "Jan 20, 2026",
        priceScore: 98,
        comfortScore: 80,
        speedScore: 95,
        notes: "Lightning-fast hop to the Middle East gateway. Perfect for desert safaris and skyscraper selfies before your next adventure.",
        bookingUrl: "https://trip.com/flights/book?deal=del-dxb-189",
        featured: true,
      },
      {
        route: "LAX ↔ JFK",
        origin: "Los Angeles",
        destination: "New York JFK",
        airline: "JetBlue",
        price: 248,
        outboundDuration: "5h 30m",
        outboundStops: 0,
        returnDuration: "6h 15m",
        returnStops: 0,
        departureDate: "Jan 8, 2026",
        returnDate: "Jan 18, 2026",
        priceScore: 92,
        comfortScore: 88,
        speedScore: 93,
        notes: "Coast-to-coast with JetBlue's famous legroom and free WiFi. Stream your way across America in comfort.",
        bookingUrl: "https://trip.com/flights/book?deal=lax-jfk-248",
        featured: true,
      },
      {
        route: "JFK ↔ FCO",
        origin: "New York JFK",
        destination: "Rome Fiumicino",
        airline: "ITA Airways",
        price: 425,
        outboundDuration: "8h 45m",
        outboundStops: 0,
        returnDuration: "9h 15m",
        returnStops: 0,
        departureDate: "Jan 22, 2026",
        returnDate: "Feb 5, 2026",
        priceScore: 88,
        comfortScore: 90,
        speedScore: 88,
        notes: "Full-service Italian carrier with complimentary wine and meals. Arrive in style for your Roman holiday.",
        bookingUrl: "https://trip.com/flights/book?deal=jfk-fco-425",
        featured: true,
      },
      {
        route: "DEL ↔ DXB",
        origin: "Delhi",
        destination: "Dubai",
        airline: "IndiGo",
        price: 195,
        outboundDuration: "3h 30m",
        outboundStops: 0,
        returnDuration: "3h 40m",
        returnStops: 0,
        departureDate: "Jan 12, 2026",
        returnDate: "Jan 25, 2026",
        priceScore: 97,
        comfortScore: 78,
        speedScore: 94,
        notes: "Budget-friendly direct flight with India's favorite low-cost carrier. More money for Dubai's gold souks!",
        bookingUrl: "https://trip.com/flights/book?deal=del-dxb-195",
        featured: true,
      },
    ];

    for (const deal of deals) {
      await ctx.db.insert("flights", deal);
    }

    return { success: true, count: deals.length };
  },
});
