import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const seedFlights = mutation({
    args: {},
    handler: async (ctx) => {
        const deals = [
            {
                route: "JFK ↔ FCO",
                origin: "New York JFK",
                destination: "Rome Fiumicino",
                airline: "Norse Atlantic",
                price: 338,
                outboundDuration: "8h 15m",
                outboundStops: 0,
                returnDuration: "9h 30m",
                returnStops: 0,
                departureDate: "Jan 15, 2026",
                returnDate: "Jan 29, 2026",
                priceScore: 95,
                comfortScore: 85,
                speedScore: 90,
                notes: "Direct Norse Atlantic red-eye—premium economy legroom at economy prices!",
                bookingUrl: "https://trip.com/flights/book?deal=jfk-fco-338",
                featured: true,
            },
            {
                route: "DEL ↔ DXB",
                origin: "Delhi",
                destination: "Dubai",
                airline: "Air India Express",
                price: 189,
                outboundDuration: "3h 25m",
                outboundStops: 0,
                returnDuration: "3h 35m",
                returnStops: 0,
                departureDate: "Jan 10, 2026",
                returnDate: "Jan 20, 2026",
                priceScore: 98,
                comfortScore: 80,
                speedScore: 95,
                notes: "Lightning-fast hop to the Middle East gateway. Perfect for short adventures.",
                bookingUrl: "https://trip.com/flights/book?deal=del-dxb-189",
                featured: true,
            },
            {
                route: "LAX ↔ JFK",
                origin: "Los Angeles",
                destination: "New York JFK",
                airline: "JetBlue",
                price: 248,
                outboundDuration: "5h 30m",
                outboundStops: 0,
                returnDuration: "6h 15m",
                returnStops: 0,
                departureDate: "Jan 8, 2026",
                returnDate: "Jan 18, 2026",
                priceScore: 92,
                comfortScore: 88,
                speedScore: 93,
                notes: "Coast-to-coast with JetBlue's famous legroom and free WiFi.",
                bookingUrl: "https://trip.com/flights/book?deal=lax-jfk-248",
                featured: true,
            },
            {
                route: "ORD ↔ LHR",
                origin: "Chicago O'Hare",
                destination: "London Heathrow",
                airline: "British Airways",
                price: 485,
                outboundDuration: "7h 50m",
                outboundStops: 0,
                returnDuration: "8h 45m",
                returnStops: 0,
                departureDate: "Feb 10, 2026",
                returnDate: "Feb 24, 2026",
                priceScore: 87,
                comfortScore: 92,
                speedScore: 89,
                notes: "Classic transatlantic service with full amenities. Winter in London!",
                bookingUrl: "https://trip.com/flights/book?deal=ord-lhr-485",
                featured: true,
            },
            {
                route: "BOM ↔ SIN",
                origin: "Mumbai",
                destination: "Singapore",
                airline: "Singapore Airlines",
                price: 312,
                outboundDuration: "5h 45m",
                outboundStops: 0,
                returnDuration: "6h 00m",
                returnStops: 0,
                departureDate: "Mar 5, 2026",
                returnDate: "Mar 15, 2026",
                priceScore: 90,
                comfortScore: 98,
                speedScore: 92,
                notes: "World-class service to the Lion City. Unmatched comfort in the skies.",
                bookingUrl: "https://trip.com/flights/book?deal=bom-sin-312",
                featured: true,
            },
        ];

        for (const deal of deals) {
            await ctx.db.insert("flights", deal);
        }

        return { success: true, count: deals.length };
    },
});
